#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua/jisaw

# link wholesale
for f in `find -E . -regex ".*\.vim$|.*\.lua$"`; do
    echo $f
    rm -rf ~/.config/nvim/$f
    ln -s ~/Developer/git/dotfiles/$f ~/.config/nvim/$f
done
